TWITTER_API_KEY = 'CwGM008PjsxFpIRdQWhYap2Tf'
TWITTER_API_KEY_SECRET = 'YmAp1KTjksaefd8ZJZIXSKp5L8JIE7wzse6daYt0PJX9c4bwaf'
TWITTER_ACCESS_TOKEN = '1503959526328119296-l8BwZBGnmJlR8Ks2fEUieif6Y6omZO'
TWITTER_ACCESS_TOKEN_SECRET = 'CQFdYKTUsvQWGWGl6ijzkIsCDBOkkdNoH8bJvGSkG9nLw'


OPENAI_API_KEY = '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'
OPENAI_TOKEN = 'MTAxMTIzOTQxMzM5ODg5NjY1MA.GgHe3H.QVnZW0etJB-m3BDS431-rWYTy3qTUhXqHdYPhI'
